---
output: pdf_document
---

This thesis addresses the problem of daily wildffire prediction in the Autonomous Community of Andalusia using spatial data processing techniques and *Machine Learning* models.  The time frame of the study is set between 2002 and 2022. Twenty-seven variables are considered in the study of five major categories: anthropological, meteorological, topographical, demographic and vegetation. The perimeters of forest fires larger than 100 *ha* occurring in Andalusia and obtained from satellite images and field data available in the Environmental Information Network of Andalusia (REDIAM) are used. Methods are implemented to process the spatial datasets collected and generate adequate samples to train predictive models, with which a sample of 21,546 records is generated and used to train the models, considering a temporal partition in training-validation-test. The models analysed were: logistic regression with penalty, logistic regression with penalty using PCA, k-*Nearest Neighbours*, linear SVM, radial SVM, decision trees and *Random Forest*. Hyperparameter tuning has been carried out usig the validation set and the performance of the tuned models on the test set has been compared usig different metrics. The *lasso* logistic regression and SVM models stood out, reaching, in the test set, an accuracy of 0.71, an area under the ROC curve of 0.795, a sensitivity of 0.729 and a specificity of 0.693. Finally, the performance of these models has been evaluated in two case studies, with promising results.

