---
output:
  pdf_document:
    keep_tex: yes
    number_sections: yes
    citation_package: natbib  # comentado usa: pandoc-citeproc
    template: latex/templateMemoriaTFE.tex
    pandoc_args: ["--metadata-file=cabecera_capitulos.yaml"]
  html_document: default
#bibliography: bib/library.bib # descomentar si: editor visual RStudio  
---

<!-- escribir 2 para capítulo 3 -->
<!-- \setcounter{chapter}{2} --> 
<!-- \pagenumbering{arabic} -->

`r xfun::file_string('cabecera_capitulos.tex')`

```{r include=FALSE}
source("cabecera_chunk_inicio.R")
```


# Capítulo 4: Cuerpo

<!-- Aquí es donde se empieza a poner interesante la cosa, se trata de aplicar las técnicas ya mencionadas a los datos. -->

## Obtención y organización de los datos

## Depuración y preprocesamiento
<!-- Depuración -->
En este caso, se ha realizado una fase previa de depuración del conjunto de datos con el objetivo de tener un conjunto de datos correcto técnicamente. Para ello, lo primero ha sido detectar, comprender y eliminar o imputar los valores faltantes, así como reajustar los tipos de las variables, codificando para ello las que así lo requiriesen en base al conocimiento previo del dominio del problema. Posteriormente, se ha un estudiado la consistencia de los datos, mediante la identificación de valores atípicos durante el análisis descriptivo del conjunto de datos.

## Análisis exploratorio

## Estudio de las variables

## Modelización

### Modelo 1
### Modelo 2

## Comparación


