---
output: pdf_document
---

En el presente trabajo fin de estudios se aborda el problema de la predicción diaria de incendios forestales en la Comunidad Autónoma de Andalucía haciendo uso de técnicas de procesamiento de datos espaciales y modelos de *Machine Learning*.  Se fija el marco temporal del estudio entre los años 2002 y 2022. Se consideran 27 variables correspondientes a 5 categorías: antropológica, meteorológica, topográfica, demográfica y de vegetación. Se usan los perímetros de incendios forestales mayores de 100 *ha* ocurridos en Andalucía y obtenidos a partir de imágenes satélite y datos de campo disponibles en la Red de Información Ambiental de Andalucía (REDIAM). Se implementan métodos para procesar los conjuntos de datos espaciales recopilados y generar muestras adecuadas para entrenar modelos predictivos, con los cuales se genera una muestra de 21.546 registros que se usa para entrenar los modelos, considerando una partición temporal en entrenamiento-validación-test. Los modelos analizados han sido: regresión logística con penalización, regresión logística con penalización usando PCA, k-*Nearest Neighbours*, SVM lineal, SVM radial, árboles de decisión y *Random Forest*. Se han ajustado los valores de los hiperparámetros evaluando el rendimiento sobre el conjunto de validación y se ha comparado el rendimiento de los modelos construidos sobre el conjunto test considerando diversas métricas. Han destacado los modelos de regresión logística *lasso* y SVM, que han obtenido los mejores resultados en el conjunto test. Finalmente, se ha evaluado el desempeño de estos modelos en dos casos prácticos, obteniendo resultados prometedores.
