---
title: "TFG_estructura"
author: "Juan Baeza Ruiz-Henestrosa"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Resumen 

# Abstract


# Capítulo 1: Introducción

## Introducción
<!-- Dar cifras para mostrar la relevancia del estudio obtenidas de la EGIF -->

## Objetivos

El objetivo de esta investigación será construir modelos que permitan predecir el riesgo de incendio forestal en la Comunidad Autónoma de Andalucía.

Subobjetivos: 

1. Construir un conjunto de datos que permita la realización de análisis y la construcción de modelos para la predicción del riesgo de incendio forestal en Andalucía a partir de un estudio previo del problema. 

2. Modelizar el riesgo de de incendio forestal usando distintos algoritmos de ML y comparar sus resultados

3. Analizar potenciales casos de interés.

## Hipótesis
1. Disminuye con la altitud
2. Aumenta con la pendiente
3. Aumenta con el NDVI
4. Aumenta con el viento
5. Aumenta con la temperatura
6. 

## Revisión bibliográfica


## Análisis del problema

<!-- Área de de estudio -->
<!-- Franja temporal del estudio -->
<!-- ¿Qué es un incendio forestal? -->




# Capítulo 2: Preliminares

<!-- Definir de forma breve y concisa todas las técnicas que serán utilizadas. -->

## Sistemas geográficos de información 

<!-- El objetivo de esta sección es que alguien que puede no estar habituado al manejo de datos espaciales pueda entender, aunque no necesariamente en detalle, las técnicas que se han utilizado hasta poder obtener un data.frame que poder utilizar para realizar todo el análisis. -->

Usar como modelo la introducción de: https://r.geocompx.org/intro

## Análisis exploratorio de los datos

## Preprocesamiento de los datos

## Herramientas


# Capítulo 3: Cuerpo

<!-- Aquí es donde se empieza a poner interesante la cosa, se trata de aplicar las técnicas ya mencionadas a los datos. -->

## Análisis exploratorio

## Estudio de las variables

## Modelización

### Modelo 1
### Modelo 2

## Comparación


# Capítulo 4: Conclusiones

# Bibliografía

# Anexos



